# Generated by Django 2.0.6 on 2018-08-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignItems',
            fields=[
                ('campaign_items_id', models.AutoField(db_column='campaign_items_id', primary_key=True, serialize=False, verbose_name='活动商品ID')),
                ('campaign_id', models.BigIntegerField(db_column='campaign_id', verbose_name='活动ID')),
                ('item_id', models.BigIntegerField(db_column='item_id', verbose_name='商品ID')),
                ('status', models.CharField(db_column='status', default='normal', max_length=255, verbose_name='数据状态')),
            ],
            options={
                'db_table': 'campaign_items',
            },
        ),
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('campaign_id', models.AutoField(db_column='campaign_id', primary_key=True, serialize=False, verbose_name='活动ID')),
                ('location', models.CharField(db_column='location', max_length=255, verbose_name='活动位置')),
                ('campaign_name', models.CharField(db_column='campaign_name', max_length=255, verbose_name='活动名字')),
                ('start_time', models.IntegerField(db_column='start_time', verbose_name='活动开始时间')),
                ('end_time', models.IntegerField(db_column='end_time', verbose_name='活动结束时间')),
                ('intorduction', models.CharField(blank=True, db_column='intorduction', max_length=1000, null=True, verbose_name='活动介绍')),
                ('campaigns_photo_id', models.CharField(db_column='campaigns_photo_id', max_length=255, verbose_name='活动图片ID')),
                ('title_photo_id', models.CharField(blank=True, db_column='title_photo_id', max_length=255, null=True, verbose_name='活动内顶部图片ID')),
                ('status', models.CharField(db_column='status', default='normal', max_length=255, verbose_name='数据状态')),
                ('create_time', models.IntegerField(db_column='create_time', default=1533628058, verbose_name='活动创建时间')),
            ],
            options={
                'db_table': 'campaigns',
            },
        ),
    ]
