# Generated by Django 2.0.6 on 2018-06-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='role',
        ),
        migrations.AddField(
            model_name='itemcomments',
            name='stars',
            field=models.SmallIntegerField(db_column='stars', default=5, verbose_name='星级'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='brand_about',
            field=models.CharField(blank=True, db_column='brand_about', max_length=255, null=True, verbose_name='品牌简介'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='brand_image',
            field=models.CharField(blank=True, db_column='brand_image', max_length=255, null=True, verbose_name='品牌图片路径'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='cn_name_abridge',
            field=models.CharField(blank=True, db_column='cn_name_abridge', max_length=255, null=True, verbose_name='品牌中文名缩写'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='en_name',
            field=models.CharField(blank=True, db_column='en_name', max_length=255, null=True, verbose_name='品牌英文名'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='form_country',
            field=models.CharField(blank=True, db_column='form_country', max_length=255, null=True, verbose_name='所属国家'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='key_word',
            field=models.CharField(blank=True, db_column='key_word', max_length=255, null=True, verbose_name='搜索关键字'),
        ),
        migrations.AlterField(
            model_name='items',
            name='brand_id',
            field=models.BigIntegerField(blank=True, db_column='brand_id', null=True, verbose_name='品牌ID'),
        ),
        migrations.AlterField(
            model_name='items',
            name='buy_count',
            field=models.IntegerField(blank=True, db_column='buy_count', null=True, verbose_name='被购买次数'),
        ),
        migrations.AlterField(
            model_name='items',
            name='capacity',
            field=models.CharField(blank=True, db_column='capacity', max_length=255, null=True, verbose_name='容量'),
        ),
        migrations.AlterField(
            model_name='items',
            name='categories_id',
            field=models.BigIntegerField(blank=True, db_column='categories_id', null=True, verbose_name='分类ID'),
        ),
        migrations.AlterField(
            model_name='items',
            name='comment_count',
            field=models.IntegerField(blank=True, db_column='comment_count', null=True, verbose_name='评论数量'),
        ),
        migrations.AlterField(
            model_name='items',
            name='create_time',
            field=models.IntegerField(db_column='create_time', default=1529052197, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='items',
            name='current_price',
            field=models.FloatField(blank=True, db_column='current_price', null=True, verbose_name='商品现价'),
        ),
        migrations.AlterField(
            model_name='items',
            name='for_people',
            field=models.CharField(blank=True, db_column='for_people', max_length=255, null=True, verbose_name='适用人群'),
        ),
        migrations.AlterField(
            model_name='items',
            name='foreign_price',
            field=models.FloatField(blank=True, db_column='foreign_price', null=True, verbose_name='国外价格'),
        ),
        migrations.AlterField(
            model_name='items',
            name='hot_value',
            field=models.IntegerField(blank=True, db_column='hot_value', null=True, verbose_name='热度值'),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_barcode',
            field=models.CharField(blank=True, db_column='item_barcode', max_length=255, null=True, verbose_name='商品条码'),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_code',
            field=models.CharField(blank=True, db_column='item_code', max_length=255, null=True, verbose_name='商品编码'),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_info',
            field=models.CharField(blank=True, db_column='item_info', max_length=255, null=True, verbose_name='商品信息'),
        ),
        migrations.AlterField(
            model_name='items',
            name='key_word',
            field=models.CharField(blank=True, db_column='key_word', max_length=255, null=True, verbose_name='搜索关键字'),
        ),
        migrations.AlterField(
            model_name='items',
            name='origin',
            field=models.CharField(blank=True, db_column='origin', max_length=255, null=True, verbose_name='生产地'),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.FloatField(blank=True, db_column='price', null=True, verbose_name='商品原价'),
        ),
        migrations.AlterField(
            model_name='items',
            name='shelf_life',
            field=models.CharField(blank=True, db_column='shelf_life', max_length=255, null=True, verbose_name='保质期'),
        ),
        migrations.AlterField(
            model_name='items',
            name='specifications_type_id',
            field=models.SmallIntegerField(blank=True, choices=[(0, '瓶'), (1, '包'), (2, '套'), (3, '片'), (4, '支'), (5, '袋'), (6, '对'), (7, '盒')], db_column='specifications_type_id', null=True, verbose_name='规格类型'),
        ),
        migrations.AlterField(
            model_name='items',
            name='update_person',
            field=models.CharField(blank=True, db_column='update_person', max_length=255, null=True, verbose_name='更新人'),
        ),
        migrations.AlterField(
            model_name='items',
            name='update_time',
            field=models.IntegerField(db_column='update_time', default=1529052197, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='items',
            name='weight',
            field=models.CharField(blank=True, db_column='weight', max_length=255, null=True, verbose_name='重量'),
        ),
        migrations.AlterField(
            model_name='member',
            name='create_time',
            field=models.IntegerField(db_column='create_time', default=1529052197),
        ),
        migrations.AlterField(
            model_name='member',
            name='update_time',
            field=models.IntegerField(db_column='update_time', default=1529052197),
        ),
    ]
